server:
    port: 9012

spring:
    application:
        name: nacos-payment-consumer

    cloud:
        nacos:
            discovery:
                server-addr: localhost:8848  # 配置nacos地址

    datasource:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://127.0.0.1:3306/db2020?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
        username: root
        password: wsw19980801

mybatis:
    mapper-locations: classpath:mapper/*.xml
    type-aliases-package: com.wsw.fusertaskmanager.entities

management:
    endpoints:
        web:
            exposure:
                include: '*'

# 使用openfeign已整合的Ribbon 设置feign客户端的超时时间
ribbon:
    # 建立连接后，从服务器读取到可用资源所用的时间
    ReadTimeout: 5000
    # 建立连接所用的时间，适用于网络状况正常的情况下，两端连接所用的时间
    ConnectTimeout: 5000