server:
    port: 8401

spring:
    application:
        name: nacos-payment-consumer

    cloud:
        nacos:
            discovery:
                server-addr: localhost:8848  # 配置nacos地址
        sentinel:
            transport:
                dashboard: localhost:9090  # sentinel dashboard地址
                port: 8719  # sentinel api port

management:
    endpoints:
        web:
            exposure:
                include: '*'